Remove nodejs
gardener/website-generator pull request #59
Opened 2020-11-18 14:08 UTC by swilen-iwanow

**What this PR does / why we need it**:
Removes the dependency to Node.js as the previous scripts written in javascript are now replaced entirely by Docforge. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-11-18 18:16 UTC, g-pavlov requested changes

2020-11-18 18:16 UTC, g-pavlov commented on .ci/build
> +export LATESTVERSIONS=($versions) # make it arr
it seems we are not using these

2020-11-18 18:16 UTC, g-pavlov commented on .ci/build
>  fi
is this necessary?

2020-11-18 18:16 UTC, g-pavlov commented on .ci/build
> +docforge -f ${CLONE}/.docforge/website.yaml -d $HUGO_CONTENT --resources-download-path __resources --hugo --github-oauth-token $GIT_OAUTH_TOKEN --github-info-destination ../data || true
The `__resources` value is the default for the `--resources-download-path ` flag so not strictly necessary here. 
```suggestion
docforge -f ${CLONE}/.docforge/website.yaml -d $HUGO_CONTENT --hugo --github-oauth-token $GIT_OAUTH_TOKEN --github-info-destination ../data || true
```

2020-11-19 14:26 UTC, swilen-iwanow commented
@g-pavlov ptal.

2020-11-19 15:04 UTC, g-pavlov approved these changes
tal
/lgtm

2020-11-19 15:09 UTC, merged